---
title: "BUAN/ECO/MNGT Topics: Mind, Markets, and Technology"
author: "Bill Foote  -- Spring 2025"
date: "`r Sys.Date()`"
bibliography: mind.bib
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Course Description

This course confronts technology's role in human society from three points of view: the economics of AI hindsight, insight, and foresight systems; the foundations of AI computational platforms in the logic and algebra of George Boole with Google Brain's Generative Pre-trained Transformers (built by the class); and  the linkage of mind, body, tools, polity as the basis for the ethics of technology, with the exemplary case of Artificial Intelligence (AI). These perspectives combine into implications for humanistic economic and management policy and practice especially in complex organizations.

## Audience

The course may be tailored to the curricular needs of advanced undergraduate and graduate students in programs of liberal arts and sciences, management, and engineering. 

## Some initial questions to spur our interest

Have the finite, yet expanding, bounds of technology become the anthropocene horizon? Within this horizon can an AI system think and be conscious of their thinking and thus be the ultimate good for humanity? If so, do AI-assisted/run markets and decision-making platforms think and are conscious and thus should we conform to the workings of markets and their platforms? Does consciousness even matter, ultimately, to markets, to technology, to the common good? Is technology just a collection of techniques or an as-if organism which prioritizes human choice? Is humanity just a brain inside an organic machine so that the mind stands to the brain as a software stands to hardware? How can creatures like ourselves think thoughts that are “about” things and reason about our reasoning (and doing, making)? How does our enchantment with technology save us? Is AI really going to be able to replace human intelligence (or has it effectively done so already)? Should we want this? Why do we need \$500 billion up front and lots of power and energy (physical and political) to underwrite such pervasive technology? Is that allocation of resource to technology as effective horizon yet another totalitarianism? What is the good of order, the value, sought by humans making machines?

## Pre-requisites

The minimal requirements as you walk into this course include these.

- A willingness to reflect on, question, and participate in substantive discussions about alternative, and sometimes competing, views about our minds, bodies, society, the decisions we make, the tools we use, including the technologies of economics, growth, progress, decline, power and authority.

- Professional writing standards, including, bibiographic, organizational logic, use of English grammar, syntax, semantics. Imagine that your essays will be published in your favorite media outlet and you do not want the editor to revise or otherwise delay publication of your fine work for anything but clarity of content.

- 5th grade arithmetic and some 9th grade algebra and how to use a pencil and paper (or their equivalents) to write and figure out the little bit of arithmetic (multiplication and addition) and algebra (elementary polynomial expressions) we will do to understand AI and its deep innards. We will build a simple Generative Pre-Trained Transformer in your notebook (and in a spreadsheet).

# Format and Assessment

The course will be conducted online and asynchronously with respect to lectures and assignments, along with opportunities to check in frequently in live sessions. Four 5 page essays (70\%), a final essay of 7 pages (20\%), and participation in class discussion boards (10\%) are required.

The class will be run in a tutorial style (see [\underline{Gilbert Highet, The Art of Teaching, p. 121)}.](https://archive.org/details/artofteaching0000gilb_h1o5/page/120/mode/2up?q=tutorial) This means at the least each student, or team of students, meets regularly with the instructor and together collaborates on the architecture of the emphasis, frameworks, content, and exposition of each essay. By emphasis is meant the economics, data analytical, and philosophical perspectives, or, in some cases two of the three, or all three. The combinations boggle the mind. 

Each essay will attend to literal (phenomenological, experiential), allegorical (normative, reasonable), tropical (moral, responsible), anagogical (what is most important to us, the good we seek) considerations. All considerations must tie back to the literal interpretation. We are not here to conform reality to our vagaries and animadversions. Or are we? This instructor would dearly love that debate!

In the millenia-old tradition, the teacher is a (kind, generous, but firm and persistent) goad to push the seemingly timid into action, and the overtly enthusiastic into focus. Our work together follows the ages old exhortation to encourage one another daily, while it is still today. Encouragement here is to "irrigate the deserts" in each of us and do so together, "not to cut down the jungles" ([\underline{C.S. Lewis, The Abolition of Man, p. 9}).](https://archive.org/details/in.ernet.dli.2015.88346/page/n17/mode/2up?q=irrigate+deserts)

## Grading Rubric for essays

All papers must be neatly typed, double-spaced, in an easily readable font (Times Roman or Arial 12pt, for example). Be sure to include your name, the date, and the assignment number on your paper. Please number your pages at the bottom right of the page in the footer and include a word count at the end and any sources consulted (not part of the 5 page requirement). Papers should be turned in at the time and date indicated on the assignments section of the course website. ALL PAPERS MUST BE SUBMITTED ELECTRONICALLY IN PORTABLE DOCUMENT FORMAT (PDF). The instructor reserves the right to view your notes, drafts, and hard copy of your work.

- 0 &– not submitted 
- 1-4 &– incomplete essay (much less than 5 pages, e.g., 3 1/2 pages _might_ indicate this condition; however, succinctness is still a virtue). No evidence of comprehension of reading materials, only restates a few facts.
- 5-6 – shows some evidence of comprehending and reflecting on the reading materials, but thesis not clearly stated upfront.
- 7-8 - shows strong evidence of comprehending and reflecting on the reading materials, and thesis
clearly stated upfront. They may show some degree of originality in their thesis, or opinions.
- 9-10 – shows strong evidence of comprehending and reflecting on the reading materials, and thesis is clearly stated upfront. The essay contains a high degree of originality, well-expressed opinions, and shows a clear, well-read understanding and mastery of the topic.
 
## Essay effort guidelines

[points out of 100 points indicate degree of effort]

- **Thesis.** Does the essay have a clear (at least complete if-then sentence(s)) central thesis with a clear (structured based on the terms of the thesis) introduction providing a road map to the reader (seciont by section)? (20)

- **Organization.** Does the essay have a clear (easy to recognize based on the thesis) overall structure? Are arguments and evidence logically sequenced and organized hierarchically? Is each paragraph in the body of the essay organized around a main idea? Are connections drawn among the key points? Does the essay present a coherent defense of your thesis? (25)

- **Content and use of evidence.** Does the introduction provide adequate (sufficient to develop the argument) background about the topic and the related controversies? Are your arguments well developed, with evidence from all the source materials, including class readings and discussions, personal observations and experience? Are counterarguments considered ( _quaestiones disputatae_, as in class)? Does the conclusion draw the essay to a close, highlighting the central points in your argument? Are sources properly cited? (30)

- **Expression.** Are ideas and information articulated in clear (predominantly active voice), fluent prose? (15)

- **Mechanics.** Is the essay free of grammatical, punctuation, and spelling errors? Is the
essay of the required length? (10)

We will work in teams and submit individual assignments and posts. Individual final grades are A-F (integer ranges): A (>95), A- (90-94), B+ (85-89), B (80-84), C+ (75-79), C (70-74), D (65-69), F (<65).

# Readings

1. [Agrawal, A., Gans, J., & Goldfarb, A. (2022). Power and prediction: The disruptive economics of artificial intelligence. Harvard Business Press.](https://www.amazon.com/Power-Prediction-Disruptive-Artificial-Intelligence/dp/B0BM4Z9TFG/ref=sr_1_1?crid=ALZNXFYMXEO5&dib=eyJ2IjoiMSJ9.wVVAdFtxTWgM9NqXl9ZAK1dISmNgRk6vHYvGue30Hbrg3vXOpl9Ss_O9LXS9EoNlvZsky89A7O87IqlpEKMTyG-kHbFIp42kK4-qdQPGaMpwoK91oLRVa8YPjTaWbiqafwmEwWBCvJqfVcx3kl4rctsZXI5cupvOEg6UuW2kL2zFL38ugY86L72sbXxwzxMgoNWLdBmmt4_ACWdEf_3qDEy_dMdiE2ekm1z4qTsiU5c.qVcxM3N4GZ-UVi7htBPScMmW1tKm8GHk21eTYfRek7o&dib_tag=se&keywords=power+prediction+ai&qid=1732739596&s=books&sprefix=power+prediction+ai%2Cstripbooks%2C91&sr=1-1) The authors examine the most basic unit of analysis: the decision whose key ingredients are prediction and judgment, both performed (so the authors believe) together in our minds. The rise of AI is shifting prediction from humans to machines, relieving people from this cognitive load while increasing the speed and accuracy of decisions. This has profound implications for system-level innovation. When these new systems emerge, they can be disruptive on a global scale. [According to the authors] decision-making confers power. In industry, power confers profits; in society, power confers control. Do we agree with any of this? We will draw some challenges with excerpts from [Hirschfeld, M. L. (2018). Aquinas and the market: Toward a humane economy. Harvard University Press.](https://www.amazon.com/Aquinas-Market-Toward-Humane-Economy/dp/0674986407/ref=sr_1_1?crid=SCZ4PQBZBXRW&dib=eyJ2IjoiMSJ9.T_hhhKwHv14UCrZQL9hLTOZefj4T4K40vL5pTD7BjRQ.DSzi7diJ-srkGAC8Z-qOCQLHFHTccp396UURnBx5fJA&dib_tag=se&keywords=aquinas+markets+hirschfeld&qid=1732746154&s=books&sprefix=aquinas+markets+hirschfeld%2Cstripbooks%2C83&sr=1-1) and [McCarraher, E. (2019). The enchantments of mammon: how capitalism became the religion of modernity. Harvard University Press.](https://www.amazon.com/Enchantments-Mammon-Capitalism-Religion-Modernity-ebook/dp/B07TFB1WVG/ref=sr_1_1?crid=XZ3Q58C444XN&dib=eyJ2IjoiMSJ9.cPt54oeiBdyCRfIU3bqmqOsySsmeQMi-PA4ssSc1FYBYQRkQJNn6WzTGzpKq74gr.-BqMRzZFofWf2jQbcMU38rDB_9bV-Jp2LNBEaR0MHWU&dib_tag=se&keywords=enchantments+of+mammon&qid=1732746235&s=books&sprefix=enchantments+of+mammon%2Cstripbooks%2C83&sr=1-1)

2. [Guardini, R. (1994). Letters from Lake Como: explorations on technology and the human race. Wm. B. Eerdmans Publishing.](https://www.google.com/books/edition/Letters_from_Lake_Como/PJGVEAAAQBAJ?hl=en&gbpv=1&dq=guardini+letters&pg=PT9&printsec=frontcover) This book collects a series of letters written by Italian-German theologian-philosopher Romano Guardini in the mid-1920s in which he works out his sense of the challenges of humanity in a culture increasingly dominated by the machine. In the Letters he physically confronts what disquieted him in contemporary civilization, the dominance of technology. Technique has created an alternative universe,self sufficient and almost independent of given nature. Only recently, with our spectacular achievements reaching an unanticipated apex, have we come to understand Heidegger’s assertion that technology, more than being our supreme accomplishment, has become a destiny that subjugates its human creators as much as their creations. With prophetic clarity and unsettling farsightedness, @guardini1994letters's letters poignantly capture the personal implications and social challenges of living in the technological age — concerns that have now come to fruition a hundred years after he first raised them. To gain clarity and challenge we will read excerpts from [Pope Francis, Encyclical Letter, Laudato si’: On Care for Our Common Home (2015).](https://www.vatican.va/content/francesco/en/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html) and [Stango, M. (2023). A Modern Genealogy of the Metaphysics of Information. Communio: International Catholic Review, 50(3), 553-586.](https://www.communio-icr.com/files/50.3_Stango_-_final_HQ.pdf)

3. [Čapek, K. (1922, 2020). RUR, or Rostrum's Universal Robots. The Theatre Guild Library edition, tr. Paul Selver. New York: Doubleday, Page, and Co.](https://www.google.com/books/edition/R_U_R_Rossum_s_Universal_Robots/Q0ZNAAAAYAAJ?hl=en&gbpv=1&dq=capek+karel+rur&pg=PA1&printsec=frontcover) R.U.R. is a 1920 science fiction play by the Czech writer Karel Čapek. "R.U.R." stands for Rossumovi Univerzální Roboti (Rossum's Universal Robots, a phrase that has been used as a subtitle in English versions). The play premiered in 1921 and introduced the word "robot" to the English language and to science fiction. The _robota_ are the laboring serfs who are made of synthetic organic material Rossum, the company, is a play on the Czech word _rozum_ which can variously mean wisdom, reason, even common sense. Yes, the world becomes a robot-economy, but I won't spoil the ending. We will experience love and utility, soul and machine, ultimate moral dilemmas, and by the way, it all comes to a head in the year 2000. The edition contains the producer's very helpful notes and is the text of the play presented in New York City at the Garrick Theatre premiering on October 9, 1922 for 184 curtains. The story continues with [Christopher Murray and Nick Johnson's comic book adaptation from the University of Dundee in 1922.](https://www.google.com/books/edition/R_U_R_Rossum_s_Universal_Robots/Q0ZNAAAAYAAJ?hl=en&gbpv=1&dq=capek+karel+rur&pg=PA1&printsec=frontcover)

4. [Foote, W.G. (2024). Notes on Computational Foundations for Technological Platforms. Unpublished notes.(Download to your browser)](https://github.com/wgfoote/mind-markets-technology/blob/main/docs/algebra.html) We explore the logic and algebra of George Boole (not Boolean algebra) and expository, and simple, examples of three pre-trained transformers all in paper and pencil, and for some on spreadsheets if you wish, and the dialectical process of Socratic logic. We use GF(2) and GF(3) arithmetic and algebra to prove Bayes Rule, resolvent and dialectical methods, and _modus tollens / ponens_ syllogisms. In the process we confront the testing of hypotheses, how data and hypotheses, and learning interact in AI, and the logic and simple practice of an AI machine from Google brain, yes, using paper and pencil. We will indeed learn to argue constructively with one another with these tools. We will rely on some facility with 5th grade arithmetic and some little bit of 9th grade algebra. We will call on excerpts (which we will simplify) from [Vaswani, A. (2017). Attention is all you need. 31st Conference on Neural Information Processing Systems (NIPS 2017), Long Beach, CA, USA.](https://user.phil.hhu.de/~cwurm/wp-content/uploads/2020/01/7181-attention-is-all-you-need.pdf) and exposure to (vintage) [Ed Eusebi and James A. Brown. 1986. APL2 and AI: a study of search. SIGAPL APL Quote Quad 16, 4 (1986), 295–300. https://doi.org/10.1145/22008.22051](https://dl.acm.org/doi/pdf/10.1145/22008.22051) with [Fordyce, K., Alfonseca, M., Brown, J., & Sullivan, G. (1992). Solving two-state logic problems with Boolean arrays: an approach unique to APL. ACM SIGAPL APL Quote Quad, 22(4), 10-11, ](https://dl.acm.org/doi/pdf/10.1145/140660.140673) all to gain some perspective and solve a puzzle.

5. [Foote, W. G. (2024). Neither a Beast Nor a God: A Philosophical Anthropology of Humanistic Management. Humanistic Management Journal, 1–45. https://doi.org/10.1007/s41463-024-00175-x](https://github.com/wgfoote/mind-markets-technology/blob/main/docs/foote-beast-god-2024-preprint.pdf). I wrote this article to house as my ongoing notes for understanding the reasons for the reasons we have when we manage, decide, organize, essentially giving ourselves to, for, with one another. The mindset (and heart-set too) here is the underpinning of a unity of mind, body, society, and technology and human dignity. Two poignant examples (the lidmen who cook coal for steel production, and the families debt-enslaved by warlords to mine rare earths to enable especially our digital technologies) goaded me into writing this essay. It continues to put my preconceptions in dire peril. We will use the categories and analytical process in this article to challenge ourselves, our interlocutors (including this article, an example of recursive thinking), and our way forward as we use technology in decision making.

\newpage

# Topical course schedule

[The several names below will be referenced in online video lectures and in the readings.]

| Topic | Lecture Precis | Notes | Readings
| :--- | :-------- | :-------- | :------ |
| **Topic 1 - May we argue a bit?**	| Nature of syllogistic reasoning. Ponens, Tollens, fallacies. Dialectics and the horns of dilemma. Algebra might "satisfy" a Robot. Quaestiones Disputatae emerge.  | Reasoning from Socrates and @striker2009aristotle, @boole1847mathematical, @peirce1870description, @shannon1938symbolic, @jaynes2003probability, @macintyre1994three, with a model from @toulmin2003uses | Read: Foote, _Logic_ ; @agrawal2022power, ch. 1; @guardini1994letters, ch. 1, @barba2023web, ch. 1 |
| **Topic 2 - Can an AI think?** | What is technology? Can we build a simple AI? Are AI-run markets thinking about something? Is the AI  the value proposition itself? The Test. The Remainder. A fork in the road. Consciousness. A technocratic paradigm emerges and countered. Build we must.| Sentient organic roboti with @capek1923rur, @turing1936machine (machine), @poole2023artificial, @turing1950mind (mind, too), but @searle1990brain  says NAY!, and also Aquinas by way of @rousselot1999intelligence, @lonergan1992insight, and @clark1962technology | Read: @agrawal2022power, ch.2, 3; @guardini1994letters, ch. 2, 3; @barba2023web, ch. 2,3  |
| **Topic 3 - What is the mind?** | Is the mind an immaterial thing? Or is the mind the brain? Or does the mind stand to the brain as a computer program stands to the hardware? Will technology save us? What comes first Power or Decisions? Spirit, matter, and odd ducks. Inversions and des-cartes before de-horse.  | Analogy of being with @pryzwara2014analogia and @hirschfeld2018aquinas, or reductionism with analytical philosophy and utilitarian rational choice with @harsanyi1978bayesian and @mill2015liberty countered by @nussbaum2001costs, (Amelie) @rorty1976literary  and @frankfurt2018freedom and @lonergan1992insight |  Read: @agrawal2022power, ch. 4, 5, 6 ; @guardini1994letters, ch. 4; @capek1923rur, Act I |
| **Topic 4 - What is knowledge?** |	Can we give some formal account of “knowledge” able to accommodate people learning new things without leaving their armchairs? Does AI change our views on the "theory of knowledge"? Love, gift, and logic. Consciousness and good and value. Making, knowing, being. AI memory, agency, text-to-action | Logical omniscience with most economists, and some discussion with some philosophers, @potter2020understanding and @lonergan1963metaphysics, Bacon from @potter1993readings, a physicist, @jaynes2003probability, technologists, @poole2023artificial, @schrage2021leadership and @schmidt2021challenge | Read: @agrawal2022power, ch. 7, 8, 9; @guardini1994letters, ch. 5 |
| **Topic 5 - Who decides what?** |	Can we construct decision alternatives consistent with data? If we can do we act on them? How can AI replace this capability? Decision tradeoffs, Intelligence and rationality, knowing, making and doing  | The classic two state - two decision model with @zellner1971introduction, @poole2023artificial, and @agrawal2022power, while @guardini1994letters and @francis2015laudato chime in | Read: @agrawal2022power, ch. 6, 7; @guardini1994letters, ch. 6; @capek1923rur, Act II |
| **Topic 6 - Can we infer -- deeply?** |	How can we possibly infer the uncertainty and predictability of market decision tradeoffs with machines? Does our simple AI align with our inference machine and with thinking at all? | An inference machine with @watanabe2013widely, @vaswani2017attention, @searle1986minds. @hirschfeld2006standard and @guardini1994letters might have something to say here | Read: @agrawal2022power, ch. 14, 15; @guardini1994letters, ch. 7, 8 |
| **Topic 7 - Are technology markets sustainable?** |	Enchanting markets, learning, and technocratic decision ethics. Markets for technology. Enchantment or magic. Back to mind, robots, humans, connectedness. | Decision inference in a behavioral model with @agrawal2022power, @sterman2010business, and @guardini1994letters. AI sustainability and corporate social responsibility with @niet2024framing and @zavyalova2023humanistic. | Read: @agrawal2022power, ch.16, 17; @guardini1994letters, ch. 9; @capek1923rur, Act III |
| **Compendium** | How do we reconcile mind, markets, and technology? How do we propose to incorporate our findings in management education, practices, and policies? Final essay preparation and presentation| A trolley ride with (Philipa) Foot by way of @cushman2006role, @livne2021cultivating and @foote2024neither when @illich2005rivers is on board while @poole2023artificial observe. | Read: @agrawal2022power, ch.18; @guardini1994letters, "Machine and Humanity"; @capek1923rur, Epilogue |

# Other matters

## Assignment Formatting

All assignments must be turned in electronically, through the learning management system, by each student. All assignments will involve writing a combination of code and actual prose. You must submit your assignment in a format which allows for the combination of the two, and the automatic execution of all your code. The easiest way to do this is to use `R Markdown`.  `R Markdown` also allows the use of interactive modeling through `Shiny` applications. 

Work submitted as Word files, unformatted plain text, etc., are not acceptable at any time during the course. Each assignment will require the submission of a pddf or html file. Managing the data base of submitted assignments throughout the course will be aided by standards including file name construction for assignment submission. To this end, every file submitted must have a file name which includes the student's name, course identifier, and clearly indicates the type of assignment (project) and its number (week). Here is the format we will use:

`yourName_courseidentifier_Assignment#.ext`, where # is the essay number and ext is the file name extension. 

For example W.G. Foote would submit a **pdf** file with this filename:

- `wgfoote_MBA6XX_Essay1.pdf`

## Course Specific Policies

Students are expected to behave in a professional and courteous manner at all times when interacting with all members of the course learning community. Respect for others is demonstrated through attendance,  meaningful participation, and punctuality. Every effort should be made to be present for each session, if not feasible, view the recording of each session, especially since weekly assignments will be made conditional on content in live sessions.

All essays must be completed and submitted by the due dates and times set out. This will allow the entire class to review and revise submissions in a timely fashion. Submissions to `lms.manhattan.edu` are based on Eastern Time (UTC +5). 

- Late submissions will result in student inability to accumulate the knowledge needed to advance to the next week's coverage of course topics. 

- Late submission will also delay necessary instructor feedback to the student in a timely fashion. 
- As the course continues to layer on more skills and capabilities, a late submission with inaccurate or incomplete requirements will only deprecate the student's ability to successfully complete future assignments, let alone the final essay.

So, don't be late. Due dates are posted in the LMS (Learning Management System) to help you pace your progress through the very quickly rolling out of the several weeks of the course term. Due dates are not deadlines. However, there is one deadline from the Registrar: all grades (including Incompletes) must be posted within 48 hours of the end of the course term.

## Academic integrity

The Manhattan University Academic Integrity Policy holds students accountable for the integrity of the work they submit. Students should be familiar with the Policy and know that it is their responsibility to learn about instructor and general academic expectations with regard to proper collection, usage, and citation of sources in written work. The policy also governs the integrity of work submitted in exams and assignments as well as the veracity of signatures on attendance sheets and other verification of participation in class activities. For more information and the complete policy, see the Manhattan University Catalog.

## Students with disabilities

If you need academic accommodations due to a disability, then you should immediately register with the Director of the Specialized Resource Center (SRC). The SRC at Manhattan University authorizes special accommodations for students with disabilities. If you have a documented disability and you wish to discuss academic accommodations, please contact the SRC within the time frame of the first week of class.

\newpage

# References consulted

